import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import AuthNav from '@/components/AuthNav';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Providers } from '@/components/Providers';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}>
        <Providers>
          <header className="flex justify-between items-center p-4 border-b border-gray-200 bg-white shadow-sm">
            <Link href="/" className="text-gray-800 text-xl font-bold no-underline">My Shop</Link>
            <nav>
              <ul className="flex space-x-5 m-0 p-0 list-none">
                <li><Link href="/" className="text-blue-600 hover:text-blue-800 no-underline">홈</Link></li>
                <li><Link href="/products" className="text-blue-600 hover:text-blue-800 no-underline">상품</Link></li>
                              <li><Link href="/cart" className="text-blue-600 hover:text-blue-800 no-underline">장바구니</Link></li>
                              <li><Link href="/orders" className="text-blue-600 hover:text-blue-800 no-underline">내 주문</Link></li>
                              <AuthNav />              </ul>
            </nav>
          </header>
          <main className="flex-grow container mx-auto p-4">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
