import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import AuthNav from '@/components/AuthNav';
import AdminProductNavLink from '@/components/AdminProductNavLink';

// Geist Sans 폰트를 설정합니다.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Geist Mono 폰트를 설정합니다.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 페이지의 메타데이터를 정의합니다. (SEO 목적)
export const metadata: Metadata = {
  title: "My Shop - E-commerce",
  description: "Generated by create next app",
};

// 모든 클라이언트 컴포넌트에 컨텍스트를 제공하는 Providers 컴포넌트를 임포트합니다.
import { Providers } from '@/components/Providers';

/**
 * 애플리케이션의 루트 레이아웃 컴포넌트입니다.
 * 모든 페이지에 공통적으로 적용되는 구조(헤더, 푸터 등)를 정의합니다.
 * @param children - 렌더링될 페이지 또는 하위 레이아웃 컴포넌트
 * @returns 애플리케이션의 기본 HTML 구조
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* body 태그에 폰트 변수와 기본 레이아웃 스타일을 적용합니다. */}
      <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}>
        {/* Providers 컴포넌트로 전체 애플리케이션을 감싸 컨텍스트를 제공합니다. */}
        <Providers>
          {/* 헤더 섹션: 로고와 메인 내비게이션을 포함합니다. */}
          <header className="flex justify-between items-center p-4 border-b border-gray-200 bg-white shadow-sm">
            {/* 로고/홈 링크 */}
            <Link href="/" className="text-gray-800 text-xl font-bold no-underline">My Shop</Link>
            {/* 메인 내비게이션 */}
            <nav>
              <ul className="flex space-x-5 m-0 p-0 list-none">
                <li><Link href="/" className="text-blue-600 hover:text-blue-800 no-underline">홈</Link></li>
                {/* 관리자에게만 보이는 상품 링크 컴포넌트 */}
                <AdminProductNavLink />
                <li><Link href="/cart" className="text-blue-600 hover:text-blue-800 no-underline">장바구니</Link></li>
                <li><Link href="/orders" className="text-blue-600 hover:text-blue-800 no-underline">내 주문</Link></li>
                {/* 인증 관련 내비게이션 (로그인/로그아웃 버튼) */}
                <AuthNav />              </ul>
            </nav>
          </header>
          {/* 메인 콘텐츠 영역: 각 페이지의 내용이 여기에 렌더링됩니다. */}
          <main className="flex-grow container mx-auto p-4">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
